### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by notnotnescap** [AGO061/BadBT#1]
Is it still in development? I really think this is an interesting project...

**Comment by caj380** [comment]
Agreed. I am excited for a release 🤞

**Comment by AGO061** [comment]
Hi, sorry for the wait. I took a break from the project but mostly due to
the lack of documentation, it's really hard to find any reference on using
HID. Still, I'll pick the project back up really soon and i wanna finish at
least a first version for good.


Thanks for the interest guys 🤙

**Comment by YawehDavid** [comment]
Very interested cool stuff

**Comment by Gacut** [comment]
This project is really bangers! 

I wish i could participate in the making but sadly, i am not good in C. I am willing to help with anything python related tho!

**Comment by notnotnescap** [comment]
I am willing to help too, let us know if you need some.

**Comment by AGO061** [comment]
Ok guys, am back and i am willing to work on this.
So, where did i stop at?
I had a demo (that i didn't upload because of the reasons i am about to say) that basically would connect to a device, but then would simply make the flipper crash and i would have to reboot everything. Not ideal at all.

But one thing i know that we definitely can do is use the code from both the bt HID plugin and the code from badUSB.
Mixing those could get us the first working version of badBT.

If you wish to help, both today and in the future, you can tag me on the official Flipper Zero discord server with: AGO061#6111

@nescapp i would be glad to be able to work with you
@Gacut I appreciate the offer but unfortunately python isn't supported on the flipper, though i will keep it in mind if i need some tools to make development faster

Have a nice one and see you all on Discord!
